# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTViNzQzZWE3NTViYjMzMjYyMDM5ZjZlZmViZjVjNWIxZjU0ZDZjNTM0ZTM2YzhmZjhmYzdlNzI3OTkzY2VhZTFmNzVlNDE4YjkzZjM3YmE3NTc1ZjBlYTM1ZWY0MzNlOWRiZDMzMzAxZTY3MzcxYTkxYmE0ZGMxMjllYTRmZGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
